In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
df = pd.read_csv("cardiac_failure/responsivenes.csv")

In [14]:
df.head()

   inpatient_number  eye_opening  verbal_response  movement consciousness  gcs
0            857781            4                5         6         Clear   15
1            743087            4                5         6         Clear   15
2            866418            4                5         6         Clear   15
3            775928            4                5         6         Clear   15
4            810128            4                5         6         Clear   15

In [15]:
df.shape

(2008, 6)

In [16]:
df.columns.tolist()

['inpatient_number',
 'eye_opening',
 'verbal_response',
 'movement',
 'consciousness',
 'gcs']

In [17]:
df.isnull().sum()

inpatient_number    0
eye_opening         0
verbal_response     0
movement            0
consciousness       0
gcs                 0
dtype: int64

In [18]:
df['inpatient_number'].duplicated().sum()

np.int64(0)

In [19]:
df.dtypes

inpatient_number    int64
eye_opening         int64
verbal_response     int64
movement            int64
consciousness         str
gcs                 int64
dtype: object

In [20]:
print("Eye Opening:")
print(sorted(df['eye_opening'].unique()))

print("\nVerbal Response:")
print(sorted(df['verbal_response'].unique()))

print("\nMovement:")
print(sorted(df['movement'].unique()))

print("\nGCS:")
print(sorted(df['gcs'].unique()))

print("\nConsciousness:")
print(df['consciousness'].unique())

Eye Opening:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4)]

Verbal Response:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

Movement:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6)]

GCS:
[np.int64(3), np.int64(4), np.int64(6), np.int64(7), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15)]

Consciousness:
<ArrowStringArray>
['Clear', 'ResponsiveToPain', 'ResponsiveToSound', 'Nonresponsive']
Length: 4, dtype: str

In [21]:
df['calculated_gcs'] = (
    df['eye_opening']
    + df['verbal_response']
    + df['movement']
)

df[df['calculated_gcs'] != df['gcs']]

Empty DataFrame
Columns: [inpatient_number, eye_opening, verbal_response, movement, consciousness, gcs, calculated_gcs]
Index: []

In [22]:
len(df[df['calculated_gcs'] != df['gcs']])

0

In [23]:
df.drop(columns=['calculated_gcs'], inplace=True)

In [24]:
df.shape

(2008, 6)

In [25]:
df['gcs'].value_counts().sort_index()

gcs
3       13
4        1
6        1
7        4
10       7
11      19
12       3
13       2
14       7
15    1951
Name: count, dtype: int64

In [26]:
df['consciousness'].value_counts()

consciousness
Clear                1974
ResponsiveToSound      19
Nonresponsive          11
ResponsiveToPain        4
Name: count, dtype: int64

In [27]:
df['eye_opening'].value_counts().sort_index()

eye_opening
1      14
2       3
3      25
4    1966
Name: count, dtype: int64